services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seazone
      POSTGRES_PASSWORD: seazone
      POSTGRES_DB: guia_hospede
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
